name: workflowPipeline

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/ruturajkolekar56/MyProject
            azure-pipeline-name: 'DevopsOrgnisation6555.GitWebApp'
            azure-devops-token: ${{ secrets.AZURE_TOKEN }}